#!/bin/bash


if [ $# -eq  1 ]
 then
	if [ $1 -gt 10 ]
	then 
		echo " Error $1 es mayor de 10"	
	else

		echo "El numero $1 es correcto. "
	fi

elif [ $# -gt 1 ]
then 
	echo "Solo pasar 1 argumento"
 fi 
 
