CREATE DATABASE Proyecto1;
USE Proyecto1;
CREATE TABLE Alumnos(Matricula varchar(255), Apellidos varchar(255), Nombres varchar(255));
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('070300610','ZALDIVAR RODRIGUEZ ',' EDGAR ALEJANDRO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('090300017','ROBLES CASANOVA ',' JIMMI ANDRES');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('090300113','CLAUSSELL ALBORNOZ ',' FLAVIO ANTONIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('090300114','VALENCIA VEGA ',' ABRAHAM ZENTLI');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('100300324','YAM LINO ',' IVAN DE JESUS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('100300334','SOLIS DIAZ ',' ERNESTO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('100300341','MORALES KU ',' BEATRIZ ADRIANA');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('100300363','CABAÑAS SUAREZ ',' JESUS AZAEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('100300379','POOL MARIN ',' IVAN GAEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('100300412','RUIZ PECH ',' ERIK FERNANDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('100300433','CANCHE RAMIREZ ',' JOSE HUMBERTO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('110300047','RAMAYO AKE ',' VICTOR ULISES');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('110300074','PALMA CAUICH ',' VEDER');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('110300095','SOTO REYES ',' IVAN AT-JARID');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('110300105','ANGEL GALEANA ',' MARCO ANTONIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('110300106','DE LA MORA BAZA ',' RHAMSES RODRIGO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('110300107','TRUJANO SORIA ',' MIGUEL ANGEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('110300147','GONZALEZ ALMENARA ',' ZACBE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('110300149','LOPEZ TUGORES ',' JUAN JOSE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300036','PEREZ GONGORA ',' JESUS ENRIQUE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300037','PEREZ GONGORA ',' CRISTHIAN JESUS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300043','VARGUEZ UICAB ',' ERIKA JAZMIN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300046','NANDEZ VASQUEZ ',' CESAR ENRIQUE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300049','VARGAS GARCIA ',' CHRISTIAN ALAN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300051','TZEL CIAU ',' ANTONY URIEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300054','BERMUDES FIGUEROA ',' OMAR');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300057','UICAB ESCALANTE ',' LUIS FERNANDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300158','PEREZ PACHECO ',' MAURO BRANDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300188','CASTAÑEDA RUANA ',' ROBERTO MISAEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300504','HERNANDEZ DIAZ ',' CECILIA IVONNE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('120300799','MENDOZA ESLAVA ',' GERMAN BENEDICTO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('130300081','MOLINA MEJIA ',' IVAN FERNANDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('130300085','PEREZ PINTO ',' DAVID ALFREDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('130300096','MOGUEL ZALDIVAR ',' RAUL ANDRES');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('130300126','NOH COCOM ',' BRIAN ASAEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('130300131','ARREDONDO CARVAJAL ',' JULIO KEMPEZ');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('130300136','BRICEÑO AGUILAR ',' JOSE LUIS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('130300450','CAMPOS NAVARRO ',' DANIEL HUMBERTO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300038','NICONOFF SANDOVAL ',' BORIS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300039','PEREZ GARCIA ',' LUIS JAVIER');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300040','PAT MAY ',' JOHANES BENJAMIN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300041','SAYON ZUMAYA ',' NESTER SIXX');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300042','OXTE DZUL ',' HAFID');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300043','RAMIREZ QUIJANO ',' ALAN MARTIN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300044','TUN DZIB ',' MARTIN ISAI');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300045','TADEO HERNANDEZ ',' EDUARDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300046','PACHECO YUPIT ',' EMMANUEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300047','RODRIGUEZ VALLE ',' SERGIO ALBERTO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300048','SOLORZANO ALCOCER ',' DANIEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300049','SALGADO GONZALEZ ',' ADAN OMAR');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300050','PEREZ GOMEZ ',' FERNANDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300055','ROBLERO CANO ',' KARLA GABRIELA');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300056','ROMERO CAAMAL ',' CESAR ALEJANDRO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300057','VARGAS GUERRERO ',' LUIS MANUEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300080','ALARCON ANGEL ',' JOSE MANUEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300081','MELENDEZ COELLO ',' PABLO FERNANDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300083','BORES RIVERA ',' ALEJANDRO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300084','CARRANZA HERRERA ',' BRUNO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300085','MORA DEHARA ',' LUIS ANDRES');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300087','CANEPA JIMENEZ ',' LUIS ALEXIS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300088','ANDRADE ALVARADO ',' RAUL ALEJANDRO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300090','CAMPOS ADAME ',' RAUL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300091','MIAM COB ',' JORGE HERMILO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300093','CAUICH NOVELO ',' CRISTIAN OSVALDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300095','ACEVEDO CASTILLO ',' LEONARDO OCTAVIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300098','GUZMAN MARTINEZ ',' KATIA MIRANDA');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300099','EK ARGAEZ ',' ROYSEL EDUARDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300101','AREVALO SALAZAR ',' JAVIER');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300103','MARTINEZ MARTINEZ ',' MICHELLE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300111','ACEVEDO SILVA ',' JULIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300129','BENITEZ RENTERAL ',' JAIR ZOEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300133','GUTIERREZ AGUILAR ',' LUIS RENE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300134','ARBELAEZ FERNANDEZ ',' GUILLERMO JOSE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300602','ARELLANO CARDONA ',' FRANCISCO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300603','LIRA MARTINEZ ',' MARIELA');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300609','MEDINA MENESES ',' JAVIER ATOCHA');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300632','AMADOR MARTINEZ ',' PABLO DANIEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300635','DIAZ LEAL ESTRADA ',' CRISTOPHER');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300650','VILLALPANDO CURIEL ',' CARLOS IGNACIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300686','CRUZ ALDECUA ',' RUBEN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('140300704','GARCIA MENA ',' ENRIQUE DE JESUS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300084','RODRIGUEZ CONCEPCION ',' LIAM');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300086','RAMOS JIMENEZ ',' NEFTALI');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300087','CAN BACAB ',' SERGIO ANTONIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300088','COLLI PERAZA ',' RODRIGO ANTONIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300089','LOPEZ ROCHA ',' EDGAR ADRIAN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300090','MENESES MARRUFO ',' CARLOS IVAN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300091','JIMENEZ PUYA ',' SEBASTIAN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300093','HERNANDEZ GUZMAN ',' JULIO CESAR');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300094','TORRES HERNANDEZ ',' EDGAR ANTONIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300096','TRUJEQUE HERNÁNDEZ ',' MARIO ENRIQUE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300097','MAGAÑA OROZCO ',' HECTOR JOSE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300099','FERNANDEZ LAGO ',' CLAUDIA SAMANTHA');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300101','MORA GOMEZ ',' IVÁN EMIGDIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300103','CHI POLANCO ',' ADRIÁN DE JESÚS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300107','GALINDO ARROYO ',' FERNANDO IVAN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300108','SÁNCHEZ PARTIDA ',' ALAN MISSAEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300109','CONSTANTINO ISNEROS ',' MOISES');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300111','CALDERÓN DÍAZ ',' ARZÚ SHAMED');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300112','GALICIA RODRIGUEZ ',' HECTOR ALONSO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300113','MARTINEZ JIMENEZ ',' ADAN DE JESUS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300114','TAH PINTO ',' ÁNGEL ALEJANDRO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300115','RAMÓN PERERA ',' GIBRÁN DE JESÚS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300117','JUAREZ OCHOA ',' JOSE DAVID');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300118','AYALA MIRANDA ',' MARTÍN JAVIER');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300119','OCHOA STECK ',' ENRIQUE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300120','ALEMAN ORTIZ ',' JORGE ISAI');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300121','PIÑA ROJAS ',' ALAN YOELL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300123','GIL GUZMAN ',' GIOVANY');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300124','MAY MANRIQUE ',' ELIAZAR DE JESÚS');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300125','GONZALEZ ORTEGA ',' JESUS SANTIAGO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300131','CATZIN AMAYA ',' SAMUEL ANTONIO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300132','VITE SANCHEZ ',' SONIA SAMARA');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300134','KUMUL BALAM ',' OSCAR NOE');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300135','ALEJO ALEJANDRO ',' MIJARES');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300156','PALACIOS TORRES ',' JULIO CESAR');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300161','CAN BACAB ',' HECTOR ARTURO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300166','HERNÁNDEZ LÓPEZ ',' JORGE IVÁN');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300171','VICTORIA BONILLA ',' FRANCISCO MANUEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300186','OJEDA RIVAS ',' GUILLERMO ALBERTO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300511','GARCIA VAZQUEZ ',' BRANDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300795','HERNÁNDEZ HERRERA ',' AMADA BETZABÉ');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300804','YAMA MARTIN ',' OSCAR RICARDO');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('150300810','LAGUNAS GUITRON ',' RAFAEL');
INSERT INTO Alumnos(Matricula, Apellidos, Nombres)  VALUES ('160100042','PALOMO ECHAVARRIA ',' MIGUEL ALEXANDER');
